name: PyInstaller Build on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Identify Changed Python Scripts
      run: |
        git fetch --depth=1 origin ${{ github.base_ref }}
        $files = git diff --name-only origin/${{ github.base_ref }}...${{ github.sha }} | Select-String '.py$'
        if (-not $files) {
          echo "No Python files have changed."
          echo "changed_files=" >> $Env:GITHUB_ENV
        } else {
          $fileList = $files -join " "
          echo "Changed Python files: $fileList"
          echo "changed_files=$fileList" >> $Env:GITHUB_ENV
        }

    - name: Install Dependencies (Optional)
      run: |
        # Add commands here to install any dependencies your script needs
        echo "Install any necessary dependencies"

    - name: Run PyInstaller on Changed Python Scripts
      if: env.changed_files != ''
      run: |
        New-Item -ItemType Directory -Force -Path dist, specs
        foreach ($file in $Env:changed_files -split " ") {
          if (Test-Path $file) {
            $file_name = [System.IO.Path]::GetFileNameWithoutExtension($file)
            echo "Building executable for $file"
            pyinstaller --onefile --name "$file_name" $file
            Move-Item "$file_name.spec" specs/
          } else {
            echo "$file does not exist."
          }
        }
      shell: pwsh
      env:
        changed_files: ${{ env.changed_files }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: executables
        path: dist/*
