name: PyInstaller Build on PR

on:
  pull_request:
    branches:
      - main # Adjust this as necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Ensure you're using the latest version
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3 # Assuming v3 for illustrative purposes, ensure you're using the latest version
      with:
        python-version: '3.x'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Identify Changed Python Scripts
      run: |
        git fetch --depth=1 origin ${{ github.base_ref }}
        files=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.sha }} | grep '\.py$')
        if [ -z "$files" ]; then
          echo "No Python files have changed."
          echo "changed_files=" >> $GITHUB_ENV
        else
          echo "Changed Python files: $files"
          echo "changed_files=$files" >> $GITHUB_ENV
        fi

    - name: Install Dependencies (Optional)
      run: |
        # Add commands here to install any dependencies your script needs
        echo "Install any necessary dependencies"

    - name: Run PyInstaller on Changed Python Scripts
      if: env.changed_files != ''
      run: |
        mkdir -p dist
        for file in ${changed_files}; do
          if [[ -f "$file" ]]; then
            base_name=$(basename "$file" .py)
            echo "Building executable for $file"
            pyinstaller --onefile --distpath dist "$file"
            echo "$base_name executable built."
          else
            echo "$file does not exist."
          fi
        done
      env:
        changed_files: ${{ env.changed_files }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: executables
        path: dist/**
