name: PyInstaller Build on PR

on:
  pull_request:
    branches:
      - main # Adjust this to match your target branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Ensures history is available for diffs

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Identify Changed Python Scripts
      id: find_scripts
      run: |
        echo "::set-output name=changed_files::$(git diff --name-only ${{ github.event.before }} ${{ github.event.pull_request.head.sha }} | grep '\.py$')"

    - name: Install Dependencies (Optional)
      run: |
        # You can add commands here to install any dependencies your script needs
        echo "Install any necessary dependencies"

    - name: Run PyInstaller on Changed Python Scripts
      run: |
        echo "${{ steps.find_scripts.outputs.changed_files }}" | while IFS= read -r file; do
          if [[ -f "$file" ]]; then
            echo "Building executable for $file"
            pyinstaller --onefile "$file"
          else
            echo "No Python files have changed."
          fi
        done
