name: PyInstaller Build on PR

on:
  pull_request:
    branches:
      - main # Adjust this as necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Updated to the latest version
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3 # Updated to the latest version, assuming v3 for illustrative purposes
      with:
        python-version: '3.x'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Identify Changed Python Scripts
      id: find_scripts
      run: |
        files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.pull_request.head.sha }} | grep '\.py$')
        if [ -z "$files" ]; then
          echo "No Python files have changed."
          # Using Environment Files to set outputs
          echo "changed_files=" >> $GITHUB_ENV
        else
          echo "Changed Python files: $files"
          # Using Environment Files to set outputs
          echo "changed_files=$files" >> $GITHUB_ENV
        fi

    - name: Install Dependencies (Optional)
      run: |
        # Add commands here to install any dependencies your script needs
        echo "Install any necessary dependencies"

    - name: Run PyInstaller on Changed Python Scripts
      if: env.changed_files != ''
      run: |
        for file in $changed_files; do
          if [[ -f "$file" ]]; then
            echo "Building executable for $file"
            pyinstaller --onefile "$file"
          else
            echo "$file does not exist."
          fi
        done
      env:
        changed_files: ${{ env.changed_files }}
