name: PyInstaller Workflow

on:
  pull_request:
    branches:
      - main # Adjust this to match your target branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Ensures history is available for diffs

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Identify Changed Python Scripts
      id: find_scripts
      run: |
        echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
        git diff --name-only ${{ github.event.before }} ${{ github.event.pull_request.head.sha }} | grep '\.py$'
        echo "EOF" >> $GITHUB_ENV

    - name: Install Dependencies (Optional)
      run: |
        # You can add commands here to install any dependencies your script needs
        echo "Install any necessary dependencies"

    - name: Run PyInstaller on Changed Python Scripts
      run: |
        while IFS= read -r file; do
          if [[ -f "$file" ]]; then
            pyinstaller --onefile "$file"
          fi
        done <<< "$CHANGED_FILES"
      env:
        CHANGED_FILES: ${{ env.CHANGED_FILES }}
