name: Build Python Executable on PR

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'

jobs:
  build-executable:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Choose the Python version as per your project's need

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Get list of changed Python files
      id: files
      uses: actions/github-script@v3
      with:
        script: |
          const payload = context.payload;
          const pullRequest = payload.pull_request;
          const listFilesOptions = github.pulls.listFiles.endpoint.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pullRequest.number
          });
          const files = await github.paginate(listFilesOptions, (response) => {
            return response.data.map(file => file.filename);
          });
          const pythonFiles = files.filter(file => file.endsWith('.py'));
          if (pythonFiles.length > 0) {
            core.setOutput('files', pythonFiles.join('\n'));
          } else {
            core.setFailed('No Python files changed.');

    - name: Build executables with PyInstaller
      if: steps.files.outputs.files
      run: |
        IFS=$'\n' read -d '' -r -a files_array <<< "${{ steps.files.outputs.files }}"
        for file in "${files_array[@]}"
        do
          echo "Building executable for $file"
          pyinstaller --onefile $file
        done

    - name: Upload executables as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: executables
        path: dist/
