name: PyInstaller Build on PR

on:
  pull_request:
    branches:
      - main # Adjust this as necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Identify Changed Python Scripts
      id: find_scripts
      run: |
        files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.pull_request.head.sha }} | grep '\.py$')
        if [ -z "$files" ]; then
          echo "No Python files have changed."
          echo "::set-output name=changed_files::"
        else
          echo "Changed Python files: $files"
          echo "::set-output name=changed_files::$files"
        fi

    - name: Install Dependencies (Optional)
      run: |
        # Add commands here to install any dependencies your script needs
        echo "Install any necessary dependencies"

    - name: Run PyInstaller on Changed Python Scripts
      if: steps.find_scripts.outputs.changed_files != ''
      run: |
        for file in ${{ steps.find_scripts.outputs.changed_files }}; do
          if [[ -f "$file" ]]; then
            echo "Building executable for $file"
            pyinstaller --onefile "$file"
          else
            echo "$file does not exist."
          fi
        done
