name: Python Syntax Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # You can choose any version compatible with your project

    - name: Install Flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Get list of changed files
      id: files
      uses: actions/github-script@v3
      with:
        script: |
          const payload = context.payload;
          const pullRequest = payload.pull_request;
          const listFilesOptions = github.pulls.listFiles.endpoint.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pullRequest.number
          });
          const files = await github.paginate(listFilesOptions, (response) => {
            return response.data.map(file => file.filename);
          });
          const pythonFiles = files.filter(file => file.endsWith('.py'));
          if (pythonFiles.length > 0) {
            core.setOutput('files', pythonFiles.join('\n'));
          } else {
            core.setFailed('No Python files changed.');
          }

    - name: Run Flake8 for syntax errors
      if: steps.files.outputs.files
      run: |
        echo "Changed Python Files:"
        echo "${{ steps.files.outputs.files }}"
        IFS=$'\n' read -d '' -r -a files_array <<< "${{ steps.files.outputs.files }}"
        for file in "${files_array[@]}"
        do
          echo "Checking syntax for $file"
          # Check only for critical syntax errors: E9, F7, F82
          flake8 $file --select=E9,F7,F82
        done
