name: Python Testing

on:
  workflow_dispatch:

jobs:
  test-scripts:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.10']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run test1
      run: python test1.py

    - name: Run test2
      run: python test2.py

# Add other steps as needed
