name: Manual Python Compatibility Tests

on:
  workflow_dispatch:

jobs:
  test-scripts:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.10']  # Corrected Python versions

    steps:
    - uses: actions/checkout@v3  # Updated action version
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3  # Updated action version
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run test1
      run: python test1.py

    - name: Run test2
      run: python test2.py
