name: Python Testing

on:
  workflow_dispatch: # Manual trigger for the workflow

jobs:
  test-scripts: # Name of the job
    runs-on: macos-latest # OS for the runner
    strategy:
      matrix:
        python-version: ['3.6', '3.10'] # Python versions as strings

    steps:
    - uses: actions/checkout@v2  # Checks-out your repository

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2  # Sets up Python environment
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run test1
      run: python test1.py

    - name: Run test2
      run: python test2.py
